# Generated by Django 4.2.2 on 2023-08-03 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drill",
            fields=[
                ("id_drill", models.AutoField(primary_key=True, serialize=False)),
                ("explanation", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id_location", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("the_address", models.CharField(max_length=255)),
                ("table_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id_match", models.AutoField(primary_key=True, serialize=False)),
                (
                    "the_current_status_a",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                            ("deleted", "deleted"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "the_current_status_b",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                            ("deleted", "deleted"),
                        ],
                        max_length=255,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("training", "training"),
                            ("competitive", "competitive"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "start_time",
                    models.IntegerField(
                        choices=[
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id_schedule", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("training", "training"),
                            ("competitive", "competitive"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "start_time",
                    models.IntegerField(
                        choices=[
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "forehand_rubber_type",
                    models.CharField(
                        choices=[
                            ("short or long pimples", "short or long pimples"),
                            ("inverted", "inverted"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "backhand_rubber_type",
                    models.CharField(
                        choices=[
                            ("short or long pimples", "short or long pimples"),
                            ("inverted", "inverted"),
                        ],
                        max_length=255,
                    ),
                ),
                ("competition_rating", models.IntegerField()),
                ("real_world_rating", models.IntegerField()),
                ("serve_feedback", models.FloatField()),
                ("receive_feedback", models.FloatField()),
                ("forehand_loop_feedback", models.FloatField()),
                ("backhand_loop_feedback", models.FloatField()),
                ("forehand_block_feedback", models.FloatField()),
                ("backhand_block_feedback", models.FloatField()),
                ("personal_feedback", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleToDrill",
            fields=[
                (
                    "id_schedule_to_drill",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "id_drill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_schedule_and_match.drill",
                    ),
                ),
                (
                    "id_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_schedule_and_match.schedule",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schedule",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="new_schedule_and_match.user",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="new_schedule_and_match.location",
            ),
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                ("id_result", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pending"), ("completed", "completed")],
                        max_length=255,
                    ),
                ),
                (
                    "id_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_schedule_and_match.match",
                    ),
                ),
                (
                    "id_player_victory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_schedule_and_match.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchToDrill",
            fields=[
                (
                    "id_match_to_drill",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "id_drill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_schedule_and_match.drill",
                    ),
                ),
                (
                    "id_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_schedule_and_match.match",
                    ),
                ),
                (
                    "id_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_schedule_and_match.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="id_player_a",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_a",
                to="new_schedule_and_match.user",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="id_player_b",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_b",
                to="new_schedule_and_match.user",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="new_schedule_and_match.location",
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id_feedback", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pending"), ("completed", "completed")],
                        max_length=255,
                    ),
                ),
                (
                    "serve_feedback",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                (
                    "receive_feedback",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                (
                    "forehand_loop_feedback",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                (
                    "backhand_loop_feedback",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                (
                    "forehand_block_feedback",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                (
                    "backhand_block_feedback",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                (
                    "personal_feedback",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                (
                    "id_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_schedule_and_match.match",
                    ),
                ),
                (
                    "id_player_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_player_a",
                        to="new_schedule_and_match.user",
                    ),
                ),
                (
                    "id_player_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_player_b",
                        to="new_schedule_and_match.user",
                    ),
                ),
            ],
        ),
    ]
