# Generated by Django 4.2.2 on 2023-08-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_schedule_and_match", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theuser",
            name="backhand_block_feedback",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="theuser",
            name="backhand_loop_feedback",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="theuser",
            name="backhand_rubber_type",
            field=models.CharField(
                choices=[
                    ("short or long pimples", "short or long pimples"),
                    ("inverted", "inverted"),
                ],
                default=("inverted", "inverted"),
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="theuser",
            name="competition_rating",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="theuser",
            name="forehand_block_feedback",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="theuser",
            name="forehand_loop_feedback",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="theuser",
            name="forehand_rubber_type",
            field=models.CharField(
                choices=[
                    ("short or long pimples", "short or long pimples"),
                    ("inverted", "inverted"),
                ],
                default=("inverted", "inverted"),
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="theuser",
            name="personal_feedback",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="theuser",
            name="real_world_rating",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="theuser",
            name="receive_feedback",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="theuser",
            name="serve_feedback",
            field=models.FloatField(default=1),
        ),
    ]
