# Generated by Django 4.2.2 on 2023-08-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_schedule_and_match", "0005_alter_theuser_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="theuser",
            table="user",
        ),
    ]
