# Generated by Django 4.2.2 on 2023-08-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_schedule_and_match", "0007_alter_theuser_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="backhand_block_feedback",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="backhand_loop_feedback",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="forehand_block_feedback",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="forehand_loop_feedback",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="personal_feedback",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="receive_feedback",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="serve_feedback",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=1,
            ),
        ),
    ]
